apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: deploy-pilot
  labels:
    app.kubernetes.io/name: deploy-pilot
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: deploy-pilot
